<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-12T10:43:14Z" name="Default suite" finished-at="2023-03-12T10:43:38Z" duration-ms="24378">
    <groups>
    </groups>
    <test started-at="2023-03-12T10:43:14Z" name="Default test" finished-at="2023-03-12T10:43:38Z" duration-ms="24378">
      <class name="test.WebTest">
        <test-method is-config="true" signature="BeforeTest()[pri:0, instance:test.WebTest@5b367418]" started-at="2023-03-12T11:43:14Z" name="BeforeTest" finished-at="2023-03-12T11:43:17Z" duration-ms="3094" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeTest -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.WebTest@5b367418]" started-at="2023-03-12T11:43:17Z" name="beforeMethod" finished-at="2023-03-12T11:43:19Z" duration-ms="1612" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test1()[pri:0, instance:test.WebTest@5b367418]" started-at="2023-03-12T11:43:19Z" name="test1" finished-at="2023-03-12T11:43:34Z" duration-ms="15203" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA['Article tag' is not correct]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 'Article tag' is not correct
	at org.testng.Assert.fail(Assert.java:94)
	at test.WebTest.test1(WebTest.java:178)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:test.WebTest@5b367418]" started-at="2023-03-12T11:43:34Z" name="beforeMethod" finished-at="2023-03-12T11:43:34Z" duration-ms="355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test2()[pri:0, instance:test.WebTest@5b367418]" started-at="2023-03-12T11:43:34Z" name="test2" finished-at="2023-03-12T11:43:38Z" duration-ms="3966" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="AfterTest()[pri:0, instance:test.WebTest@5b367418]" started-at="2023-03-12T11:43:38Z" name="AfterTest" finished-at="2023-03-12T11:43:38Z" duration-ms="121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterTest -->
      </class> <!-- test.WebTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
